blog/views/auth.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.exceptions import NotFound
from werkzeug.security import generate_password_hash, check_password_hash

from blog.extensions import login_manager, db
from blog.models.user import User
from blog.forms.user import UserRegisterForm, LoginForm

auth_app = Blueprint("auth_app", __name__)


@login_manager.unauthorized_handler
def unauthorized():
    return render_template('index.html')


@auth_app.route("/login", methods=["GET", "POST"], endpoint="login")
def login():
    if current_user.is_authenticated:
        return render_template('index.html')

    form = LoginForm(request.form)

    if request.method == "POST" and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).one_or_none()
        password = request.form.get('password')
        if user is None:
            return render_template("auth/login.html", form=form, error="username doesn't exist")
        if not not check_password_hash(user.password, password):
            return render_template("auth/login.html", form=form, error="invalid username or password")

        login_user(user)
        return render_template('index.html')

    return render_template("auth/login.html", form=form)


@auth_app.route("/login-as/", methods=["GET", "POST"], endpoint="login-as")
def login_as():
    if not (current_user.is_authenticated and current_user.is_staff):
        # non-admin users should not know about this feature
        raise NotFound

    if request.method == "GET":
        return render_template("auth/login_as.html")

    username = request.form.get("username")
    if not username:
        return render_template("auth/login_as.html", error="username not passed")

    user = User.query.filter_by(username=username).one_or_none()
    if user is None:
        return render_template("auth/login_as.html", error=f"no user {username!r} found")

    login_user(user)
    return render_template('index.html')


@auth_app.route("/register/", methods=["GET", "POST"], endpoint="register")
def register():
    if current_user.is_authenticated:
        return redirect(url_for("index"))

    form = UserRegisterForm(request.form)
    errors = []
    if request.method == "POST" and form.validate_on_submit():
        if User.query.filter_by(username=form.username.data).count():
            form.username.errors.append("username already exists!")
            return render_template("auth/register.html", form=form)

        if User.query.filter_by(email=form.email.data).count():
            form.email.errors.append("email already exists!")
            return render_template("auth/register.html", form=form)

        _user = User(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            username=form.username.data,
            email=form.email.data,
            is_staff=False,
            password=generate_password_hash(form.password.data),
        )
        db.session.add(_user)
        db.session.commit()
        login_user(_user)

    return render_template('auth/register.html', form=form, errors=errors,)


@auth_app.route("/logout/")
@login_required
def logout():
    logout_user()
    return render_template('index.html')


@auth_app.route("/secret/")
@login_required
def secret_view():
    return "Super secret data"


__all__ = [
    "login_manager",
    "auth_app",
]

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block css %}
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    {% endblock %}

    <title>
        {% block title %}
            Base
        {% endblock %}
    </title>
  </head>

  <body>
   <div class="parrent">
      {% include 'navbar.html' %}
        <div class="container">
            {% block body %}{% endblock %}
        </div>
  </div>

  {% block js %}
      <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  {% endblock %}
</html>

blog/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Index Page
{% endblock %}

{% block body %}
    <h1>Welcome to my blog!</h1>
    <h1>
        Hello
        {%  if current_user.is_authenticated %}
            {{ current_user.username }}
        {% else %}
            anon
        {% endif %}
    </h1>
{%  endblock %}

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" href="{{ url_for('users_app.list') }}">Users</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('articles_app.list') }}">Articles</a>
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-item">
              <a class="nav-link" href="{{ url_for('articles_app.create') }}">Create article</a>
        </li>
        {% endif %}
      </ul>
    </div>
    <div class="navbar-nav ms-auto">
    {% if current_user.is_authenticated %}
        <a class="nav-link" href="{{ url_for('auth_app.logout') }}">Logout</a>
    {% endif %}

    {% if not current_user.is_authenticated %}
        {% for (endpoint, label) in [('auth_app.login', 'Login'), ('auth_app.register',
            'Register'), ('authors_app.list', 'Authors'),] %}
        <a href="{{ url_for(endpoint) }}"
            class="nav-link {% if request.endpoint == endpoint -%}active{%- endif %}">
                {{ label }}
        </a>
        {% endfor %}
    {% endif %}

    </div>
  </div>
</nav>